title: Open Athena
logo: athena_thumb.jpg
description: Open Athena is a project to enable precision indirect fires that disrupt conventional combined arms warfare
show_downloads: true
theme: jekyll-theme-minimal
