title: Open Athena
logo: athena_thumb.jpg
description: Open Athena is a project which allows consumer and professional drones to spot precise locations through their images
theme: jekyll-theme-minimal
